import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import WalletProviderWrapper from "@/Wallet/privy/WalletProviderWrapper";
import {
  SITE_URL,
  SITE_NAME,
  DEFAULT_TITLE,
  DEFAULT_DESCRIPTION,
  DEFAULT_KEYWORDS,
  organizationJsonLd,
} from "@/lib/seo";

// "dev": "next dev --turbopack",

import "swiper/css";
import "@/style/globals.css";
import "swiper/css/navigation";
import "swiper/css/pagination"; // 👈 You MUST import this for dots to show

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  // `default` is used on pages that don't set their own title; `template`
  // brands every child page's title, e.g. "Contact Us | United4Change".
  title: {
    default: DEFAULT_TITLE,
    template: `%s | ${SITE_NAME}`,
  },
  description: DEFAULT_DESCRIPTION,
  keywords: DEFAULT_KEYWORDS,
  authors: [{ name: SITE_NAME }],
  applicationName: SITE_NAME,
  alternates: {
    canonical: SITE_URL,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  openGraph: {
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
    url: SITE_URL,
    siteName: SITE_NAME,
    // og image is generated by src/app/opengraph-image.tsx (1200x630 PNG)
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
  },
  icons: {
    icon: [
      { url: "/icons/u4c-logo.svg", type: "image/svg+xml" },
      { url: "/icons/u4c-192x192.png", type: "image/png", sizes: "192x192" },
    ],
    apple: "/icons/u4c-192x192.png",
  },
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: SITE_NAME,
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Organization structured data — powers rich results / knowledge panel
            and disambiguates us from the unrelated united4change.org NGO. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(organizationJsonLd()),
          }}
        />

        {/* Boxicons icon font. Preconnect shaves latency off this third-party
            request. Consider self-hosting these icons to remove the external
            dependency entirely (better Core Web Vitals). */}
        <link rel="preconnect" href="https://unpkg.com" crossOrigin="" />
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <WalletProviderWrapper>{children}</WalletProviderWrapper>
      </body>
    </html>
  );
}
