"use client";

import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import {
  useGetProfileBackgroundTaskQuery,
  useGetProfileMutation,
} from "@/redux/api/main";
import { useDispatch, useSelector } from "react-redux";
import { RootState } from "@/redux/store";
import { setOnline, setOrganization, setUser } from "@/redux/slice/users";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { online } = useSelector((state: RootState) => state.user);
  const router = useRouter();

  const { isLoading, data, refetch, error } = useGetProfileBackgroundTaskQuery(
    {
      params: {}, // ✅ object, not string
    },
    {
      // pollingInterval: 60000, // every 60 seconds
      // refetchOnFocus: true,
      // refetchOnReconnect: true,
    }
  );

  const [navigation_list, setNavigation_list] = useState<
    Array<{ path: string; title: string; active: boolean }>
  >([
    { path: "/dashboard", title: "Overview", active: false },
    { path: "/dashboard/campaign", title: "Campaign", active: false },
    { path: "/dashboard/profile", title: "Profile", active: false },
    { path: "/dashboard/transactions", title: "Transactions", active: false },
    { path: "/dashboard/treasury", title: "Treasury", active: false },
    { path: "/dashboard/setting", title: "Setting", active: false },
  ]);

  const currentPath = usePathname();
  const dispatch = useDispatch();

  function trim_slash(path: string): string {
    return path.replace(/\/+$/, "");
  }

  useEffect(() => {
    if (online === false) return;

    (async () => {
      try {
        const new_data = await refetch();

        if ("error" in new_data) return;

        console.log("====================================");
        console.log(new_data);
        console.log("====================================");

        dispatch(setOnline(true));
        dispatch(setUser(new_data?.data || {}));
        dispatch(setOrganization(new_data?.data?.user?.is_organization));
      } catch (err) {
        console.error("Error fetching data:", err);
      }
    })();

    return () => {};
  }, [currentPath]);

  useEffect(() => {
    if (online === false) return router.push("/sign-in");

    return () => {};
  }, [online]);

  console.log("====================================");
  console.log(data);
  console.log("====================================");

  return (
    <div className="flex min-h-screen">
      <div className="min-w-[15rem] min-h-screen hidden lg:block bg-[#0000000a]/30 border-r-2 border-[#0000000a]/50">
        <div className="flex flex-col gap-5 mt-5 pl-5">
          {navigation_list.map((navigation, index) => (
            <Link key={index} href={navigation.path}>
              <p
                className={`rounded-l-lg ${
                  index === 0
                    ? trim_slash(currentPath) === navigation.path
                      ? "bg-[#812880] text-white"
                      : "text-black hover:bg-[#812880]/5"
                    : currentPath.includes(navigation.path)
                    ? "bg-[#812880] text-white"
                    : "text-black hover:bg-[#812880]/5"
                } py-3 px-5`}
              >
                {navigation.title}
              </p>
            </Link>
          ))}
        </div>
      </div>

      <div className="w-full lg:w-[calc(100%-15rem)] h-full py-5">
        {children}
      </div>
    </div>
  );
}
