"use client";

import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useGetKycMutation, useGetProfileMutation } from "@/redux/api/main";
import { useDispatch, useSelector } from "react-redux";
import { RootState } from "@/redux/store";
import {
  setKyc,
  setOnline,
  setOrganization,
  setUser,
} from "@/redux/slice/users";
import { RiHome4Line, RiProfileLine } from "react-icons/ri";
import dynamic from "next/dynamic";
import { FaLayerGroup } from "react-icons/fa";
import { LuListTodo, LuSettings } from "react-icons/lu";
import { GiReceiveMoney } from "react-icons/gi";
import { TbFileSettings } from "react-icons/tb";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// ✅ Define DynamicNav within the client component scope
const DynamicNav = dynamic(() => import("@/components/Nav"), {
  ssr: false, // Prevents Nav from being processed during the server build
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { online, kyc, organization, refetch } = useSelector(
    (state: RootState) => state.user,
  );
  const router = useRouter();

  const currentPath = usePathname();
  const dispatch = useDispatch();

  const [Get_Profile, {}] = useGetProfileMutation();
  const [Get_Kyc, {}] = useGetKycMutation();

  const [navigation_list, setNavigation_list] = useState<
    Array<{ path: string; title: string; active: boolean; icon: any }>
  >([
    {
      path: "/dashboard",
      title: "Overview",
      active: false,
      icon: <RiHome4Line className="text-[1.5rem]" />,
    },
    {
      path: "/dashboard/campaign",
      title: "Campaign",
      active: false,
      icon: <FaLayerGroup className="text-[1.5rem]" />,
    },
    {
      path: "/dashboard/transactions",
      title: "Transactions",
      active: false,
      icon: <LuListTodo className="text-[1.5rem]" />,
    },
    {
      path: "/dashboard/treasury",
      title: "Treasury",
      active: false,
      icon: <GiReceiveMoney className="text-[1.5rem]" />,
    },
    {
      path: "/dashboard/setting",
      title: "Setting",
      active: false,
      icon: <LuSettings className="text-[1.5rem]" />,
    },
  ]);

  function trim_slash(path: string): string {
    return path.replace(/\/+$/, "");
  }

  useEffect(() => {
    if (online === false) return;

    (async () => {
      try {
        const profile = await Get_Profile({ params: {} });
        const kyc_res =
          kyc?.verified === false
            ? await Get_Kyc({ params: {} })
            : { error: true };

        if (!("error" in kyc_res) && organization === true) {
          const kyc_status = { value: true };
          const requirements = kyc_res?.data?.requirements;

          for (let i = 0; i < requirements?.length; i++) {
            const status = requirements[i]?.status;
            if (!(status === "pending" || status === "approved"))
              kyc_status.value = false;
          }

          const kyc_data = { verified: kyc_status.value, data: requirements };
          console.log(kyc_data);
          dispatch(setKyc(kyc_data));
        }

        if ("error" in profile) return;

        // console.log("====================================");
        // console.log("profile");
        // console.log("profile");
        // console.log("profile");
        // console.log("profile");
        // console.log(profile);
        // console.log(kyc_res);
        // console.log(kyc);
        // console.log("====================================");

        dispatch(setOnline(true));
        dispatch(setUser(profile?.data || {}));
        dispatch(setOrganization(profile?.data?.user?.is_organization));
      } catch (err) {
        console.error("Error fetching data:", err);
      }
    })();

    return () => {};
  }, [currentPath, refetch]);

  useEffect(() => {
    if (online === false) return router.push("/sign-in");

    return () => {};
  }, [online]);

  // console.log("kyc");
  // console.log("kyc");
  // console.log(kyc);

  return (
    <div className="flex min-h-screen">
      <div className="hidden md:block min-w-[5.6rem] max-w-[5.6rem] w-[5.6rem] min-h-screen relative">
        <div
          id="dashboard-navigation"
          className="flex flex-col gap-5 pt-5 px-5"
        >
          <Link
            href={"/"}
            className="relative flex flex-col items-center justify-center"
          >
            <div id="dashboard-navigation-logo" className="">
              <Image
                src={"/icons/u4c-logo.svg"}
                alt=""
                width={50}
                height={50}
                className="w-10"
              />
            </div>

            <div className="w-full h-px mt-3 mb-2 bg-[#c5c5c5]"></div>
          </Link>

          {navigation_list.map((navigation, index) => (
            <Link
              key={index}
              href={navigation.path}
              className={`rounded-full flex items-center gap-2 ${
                trim_slash(currentPath) === navigation.path
                  ? "gradient-cto text-white"
                  : "text-black hover:bg-[#812880]/5"
              } py-3 px-3`}
            >
              <div className={``}>{navigation.icon}</div>

              <p
                id="dashboard-navigation-title"
                className="font-semibold text-[1.0rem]"
              >
                {navigation.title}
              </p>
            </Link>
          ))}
        </div>
      </div>

      <div className="w-full md:w-[calc(100%-5.6rem)] h-full">
        {currentPath.includes("dashboard") && (
          <DynamicNav isDashboard={currentPath.includes("dashboard")} />
        )}

        <div className="py-5">{children}</div>
      </div>
    </div>
  );
}
